"""Splunk-specific source adapter boundary."""

from alert2ir.adapters.splunk.app import (
    MAX_REQUEST_BODY_BYTES,
    create_splunk_adapter_app,
)
from alert2ir.adapters.splunk.auth import (
    AuthenticationError,
    compute_signature,
    signing_input,
    verify_signature,
)
from alert2ir.adapters.splunk.client import (
    Alert2IRClient,
    Alert2IRDeliveryResult,
    DeliveryClassification,
)
from alert2ir.adapters.splunk.idempotency import (
    FINDING_IDENTITY_SCHEMA,
    IDEMPOTENCY_KEY_PREFIX,
    finding_identity_bytes,
    finding_identity_digest,
    finding_identity_document,
    idempotency_key,
)
from alert2ir.adapters.splunk.mapping import (
    CANONICAL_SOURCE,
    SIGMA_LEVEL_MAPPING_SCHEMA,
    build_evidence,
    canonicalize,
    normalize_hostname,
    normalize_sigma_severity,
    normalize_splunk_finding,
    normalize_timestamp,
    to_canonical_alert,
)
from alert2ir.adapters.splunk.models import (
    CHANNEL_MAX_LENGTH,
    EVIDENCE_REFERENCE_MAX_LENGTH,
    HOSTNAME_MAX_LENGTH,
    IMAGE_MAX_LENGTH,
    PARENT_IMAGE_MAX_LENGTH,
    PROCESS_GUID_MAX_LENGTH,
    RULE_TITLE_MAX_LENGTH,
    SOURCE_MAX_LENGTH,
    SOURCETYPE_MAX_LENGTH,
    SPLUNK_FINDING_SCHEMA,
    TARGET_FILENAME_MAX_LENGTH,
    CanonicalizedSplunkFinding,
    NormalizedSplunkFinding,
    SigmaLevel,
    SplunkDetectionMetadata,
    SplunkEvent,
    SplunkFinding,
)

__all__ = [
    "Alert2IRClient",
    "Alert2IRDeliveryResult",
    "AuthenticationError",
    "CANONICAL_SOURCE",
    "CHANNEL_MAX_LENGTH",
    "CanonicalizedSplunkFinding",
    "DeliveryClassification",
    "EVIDENCE_REFERENCE_MAX_LENGTH",
    "FINDING_IDENTITY_SCHEMA",
    "HOSTNAME_MAX_LENGTH",
    "IDEMPOTENCY_KEY_PREFIX",
    "IMAGE_MAX_LENGTH",
    "MAX_REQUEST_BODY_BYTES",
    "NormalizedSplunkFinding",
    "PARENT_IMAGE_MAX_LENGTH",
    "PROCESS_GUID_MAX_LENGTH",
    "RULE_TITLE_MAX_LENGTH",
    "SIGMA_LEVEL_MAPPING_SCHEMA",
    "SOURCE_MAX_LENGTH",
    "SOURCETYPE_MAX_LENGTH",
    "SPLUNK_FINDING_SCHEMA",
    "SigmaLevel",
    "SplunkDetectionMetadata",
    "SplunkEvent",
    "SplunkFinding",
    "TARGET_FILENAME_MAX_LENGTH",
    "build_evidence",
    "canonicalize",
    "compute_signature",
    "create_splunk_adapter_app",
    "finding_identity_bytes",
    "finding_identity_digest",
    "finding_identity_document",
    "idempotency_key",
    "normalize_hostname",
    "normalize_sigma_severity",
    "normalize_splunk_finding",
    "normalize_timestamp",
    "signing_input",
    "to_canonical_alert",
    "verify_signature",
]
