[Service]
WorkingDirectory=/srv/alert2ir-observability/alloy
ExecStart=
ExecStart=/usr/bin/alloy run --server.http.listen-addr=127.0.0.1:12345 --storage.path=/srv/alert2ir-observability/alloy /etc/alloy/config.alloy
